version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    docker:
      - image: themattrix/tox
    executor: python/default
    steps:
      - checkout
      - run: pip install tox
      - run:
          command: tox
          name: Test

workflows:
  main:
    jobs:
      - test
